# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane For Firebase Distribution"
  lane :distribute do
    sh "cd .. && flutter clean"
    sh "cd .. && flutter build apk --split-per-abi --release"
    firebase_app_distribution(
      app: ENV["APP_ID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-arm64-v8a-release.apk",
      testers: "mocourses2003@gmail.com",
      release_notes: "New build from Fastlane"
    )
  end
end