name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - login-signup

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo codes
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up Ruby (for Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build and distribute the app
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
        run: |
          bundle exec fastlane android distribute
        working-directory: android